In [38]:
# pip install netron # netron <model>
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, concatenate
from tensorflow.keras.models import Model
import numpy as np
(xTrain, yTrain), (xVal, yVal) = tf.keras.datasets.mnist.load_data()
xTrain, yTrain = xTrain[:1000].reshape(-1,784)/255., yTrain[:1000]
xVal, yVal = xVal[:1000].reshape(-1,784)/255., yVal[:1000]
noise = np.random.random((1000,1))
print(xTrain.shape, yTrain.shape, xVal.shape, yVal.shape, noise.shape)

(1000, 784) (1000,) (1000, 784) (1000,) (1000, 1)


In [60]:
# multiple inputs
inputA = Input(shape=(784,))
x = Dense(64, activation='relu')(inputA)
x = Dense(10, activation='relu')(x)

inputB = Input(shape=(1,))
y = Dense(4, activation='relu')(inputB)
y = Dense(4, activation='relu')(y)

z = concatenate([x,y])
z = Dense(64, activation="relu")(z)
z = Dense(1)(z)
model = Model(inputs=[inputA, inputB], outputs=z)
model.compile(optimizer=tf.keras.optimizers.Adam(), loss='mse')
model.summary()

Model: "model_27"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_28 (InputLayer)           [(None, 784)]        0                                            
__________________________________________________________________________________________________
input_29 (InputLayer)           [(None, 1)]          0                                            
__________________________________________________________________________________________________
dense_76 (Dense)                (None, 64)           50240       input_28[0][0]                   
__________________________________________________________________________________________________
dense_78 (Dense)                (None, 4)            8           input_29[0][0]                   
___________________________________________________________________________________________

In [40]:
history = model.fit([xTrain,noise], yTrain, validation_data=([xVal,noise], yVal), epochs=100, 
    batch_size=128, callbacks=[tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3,
    min_delta=0.1, restore_best_weights=True)])

Epoch 1/100
8/8 [==============================] - 0s 16ms/step - loss: 27.4082 - val_loss: 23.8064
Epoch 2/100
8/8 [==============================] - 0s 8ms/step - loss: 22.3682 - val_loss: 16.4101
Epoch 3/100
8/8 [==============================] - 0s 8ms/step - loss: 14.0333 - val_loss: 8.7280
Epoch 4/100
8/8 [==============================] - 0s 25ms/step - loss: 10.0483 - val_loss: 7.9225
Epoch 5/100
8/8 [==============================] - 0s 9ms/step - loss: 8.3838 - val_loss: 6.3691
Epoch 6/100
8/8 [==============================] - 0s 9ms/step - loss: 6.5621 - val_loss: 5.2282
Epoch 7/100
8/8 [==============================] - 0s 8ms/step - loss: 5.1062 - val_loss: 4.7771
Epoch 8/100
8/8 [==============================] - 0s 8ms/step - loss: 4.3999 - val_loss: 4.6419
Epoch 9/100
8/8 [==============================] - 0s 9ms/step - loss: 4.0607 - val_loss: 4.5886
Epoch 10/100
8/8 [==============================] - 0s 9ms/step - loss: 3.7811 - val_loss: 4.4503
Epoch 11/100
8/8 [===

In [41]:
model.predict([xTrain[0].reshape(1,-1), np.random.random((1,1))])

array([[4.2541447]], dtype=float32)

In [61]:
model.save("forkInput.h5")

In [48]:
# multiple outputs
inputL = Input(shape=(784,))
x = Dense(64, activation='relu')(inputL)
y = Dense(10, activation='relu')(x)
z = Dense(1)(x)
model = Model(inputs=inputL, outputs=[y,z])
model.compile(optimizer=tf.keras.optimizers.Adam(), loss=['mse','mse'])
model.summary()

Model: "model_22"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_19 (InputLayer)           [(None, 784)]        0                                            
__________________________________________________________________________________________________
dense_50 (Dense)                (None, 64)           50240       input_19[0][0]                   
__________________________________________________________________________________________________
dense_51 (Dense)                (None, 10)           650         dense_50[0][0]                   
__________________________________________________________________________________________________
dense_52 (Dense)                (None, 1)            65          dense_50[0][0]                   
Total params: 50,955
Trainable params: 50,955
Non-trainable params: 0
_____________________

In [49]:
history = model.fit(xTrain, [yTrain,noise], validation_data=(xVal, [yVal,noise]), epochs=100, 
    batch_size=128, callbacks=[tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3,
    min_delta=0.1, restore_best_weights=True)])

Epoch 1/100
8/8 [==============================] - 0s 18ms/step - loss: 24.5572 - dense_51_loss: 24.2419 - dense_52_loss: 0.3154 - val_loss: 19.6488 - val_dense_51_loss: 19.4374 - val_dense_52_loss: 0.2114
Epoch 2/100
8/8 [==============================] - 0s 9ms/step - loss: 18.3844 - dense_51_loss: 18.2198 - dense_52_loss: 0.1647 - val_loss: 14.4070 - val_dense_51_loss: 14.2196 - val_dense_52_loss: 0.1874
Epoch 3/100
8/8 [==============================] - 0s 9ms/step - loss: 14.0296 - dense_51_loss: 13.8835 - dense_52_loss: 0.1461 - val_loss: 10.5956 - val_dense_51_loss: 10.4321 - val_dense_52_loss: 0.1635
Epoch 4/100
8/8 [==============================] - 0s 9ms/step - loss: 10.5292 - dense_51_loss: 10.3955 - dense_52_loss: 0.1337 - val_loss: 7.9306 - val_dense_51_loss: 7.7683 - val_dense_52_loss: 0.1623
Epoch 5/100
8/8 [==============================] - 0s 10ms/step - loss: 8.3359 - dense_51_loss: 8.2084 - dense_52_loss: 0.1275 - val_loss: 6.7043 - val_dense_51_loss: 6.5565 - val_d

8/8 [==============================] - 0s 8ms/step - loss: 2.0691 - dense_51_loss: 2.0053 - dense_52_loss: 0.0638 - val_loss: 3.6842 - val_dense_51_loss: 3.5659 - val_dense_52_loss: 0.1183
Epoch 42/100
8/8 [==============================] - 0s 10ms/step - loss: 2.0289 - dense_51_loss: 1.9641 - dense_52_loss: 0.0648 - val_loss: 3.6326 - val_dense_51_loss: 3.5168 - val_dense_52_loss: 0.1158
Epoch 43/100
8/8 [==============================] - 0s 9ms/step - loss: 2.0004 - dense_51_loss: 1.9377 - dense_52_loss: 0.0626 - val_loss: 3.6139 - val_dense_51_loss: 3.4991 - val_dense_52_loss: 0.1148
Epoch 44/100
8/8 [==============================] - 0s 8ms/step - loss: 1.9475 - dense_51_loss: 1.8841 - dense_52_loss: 0.0634 - val_loss: 3.6009 - val_dense_51_loss: 3.4850 - val_dense_52_loss: 0.1158
Epoch 45/100
8/8 [==============================] - 0s 8ms/step - loss: 1.8958 - dense_51_loss: 1.8332 - dense_52_loss: 0.0626 - val_loss: 3.5975 - val_dense_51_loss: 3.4826 - val_dense_52_loss: 0.1150
Ep

In [51]:
model.predict(xTrain[0].reshape(1,-1))

[array([[4.585515 , 4.666171 , 4.5040517, 4.271038 , 4.3687186, 4.5968385,
         4.584263 , 4.5527825, 4.1127515, 4.5533705]], dtype=float32),
 array([[0.49326444]], dtype=float32)]

In [52]:
model.save("forkOutput.h5")

In [62]:
# multiple hidden
inputL = Input(shape=(784,))
x = Dense(64)(inputL)
y = Dense(64)(inputL)
z = concatenate([x,y])
z = Dense(10)(z)
model = Model(inputL, z)
model.compile(optimizer=tf.keras.optimizers.Adam(), loss='mse')
model.summary()

Model: "model_28"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_30 (InputLayer)           [(None, 784)]        0                                            
__________________________________________________________________________________________________
dense_82 (Dense)                (None, 64)           50240       input_30[0][0]                   
__________________________________________________________________________________________________
dense_83 (Dense)                (None, 64)           50240       input_30[0][0]                   
__________________________________________________________________________________________________
concatenate_11 (Concatenate)    (None, 128)          0           dense_82[0][0]                   
                                                                 dense_83[0][0]            

In [63]:
history = model.fit(xTrain, yTrain, validation_data=(xVal, yVal), epochs=100, 
    batch_size=128, callbacks=[tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3,
    min_delta=0.1, restore_best_weights=True)])

Epoch 1/100
8/8 [==============================] - 0s 15ms/step - loss: 18.4460 - val_loss: 9.3522
Epoch 2/100
8/8 [==============================] - 0s 8ms/step - loss: 10.2493 - val_loss: 8.0864
Epoch 3/100
8/8 [==============================] - 0s 9ms/step - loss: 7.8836 - val_loss: 6.0717
Epoch 4/100
8/8 [==============================] - 0s 8ms/step - loss: 6.0142 - val_loss: 5.4015
Epoch 5/100
8/8 [==============================] - 0s 8ms/step - loss: 5.0649 - val_loss: 5.0186
Epoch 6/100
8/8 [==============================] - 0s 11ms/step - loss: 4.5858 - val_loss: 4.9899
Epoch 7/100
8/8 [==============================] - 0s 10ms/step - loss: 4.3525 - val_loss: 4.8260
Epoch 8/100
8/8 [==============================] - 0s 9ms/step - loss: 4.1366 - val_loss: 4.7360
Epoch 9/100
8/8 [==============================] - 0s 11ms/step - loss: 3.9643 - val_loss: 4.5664
Epoch 10/100
8/8 [==============================] - 0s 9ms/step - loss: 3.7923 - val_loss: 4.4673
Epoch 11/100
8/8 [=====

In [64]:
model.predict(xTrain[0].reshape(1,-1))

array([[4.290557 , 4.0267296, 4.236226 , 4.2261214, 4.3456116, 4.0416994,
        4.236514 , 4.0841002, 4.151796 , 4.3222246]], dtype=float32)

In [65]:
model.save("forkHidden.h5")